<a href="https://colab.research.google.com/github/pyluis/Learning_Projects/blob/master/Churn_Modeling_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 1 Import Packages 

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Step 2 Data preprocessing


Import Data 


In [ ]:
data = pd.read_csv('Churn_Modelling.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
X = data.drop(['RowNumber','CustomerId','Surname','Exited'],axis=1).values

In [ ]:
y = data['Exited'].values

In [ ]:
X.shape

(10000, 10)

In [ ]:
y.shape

(10000,)

## Encode categorical data

Label Encoding Gender

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the Geography Column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],remainder= 'passthrough')
X= np.array(ct.fit_transform(X))

In [ ]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

Split Train and Test Data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# Step 3 Building the ANN

 ## Intialize the ANN

In [ ]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Add the Second Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Add output Layer


In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Step 4 Train the ANN

Compiling the ANN

In [ ]:
 ann.compile(optimizer= 'adam', loss='binary_crossentropy' , metrics=['accuracy'] )

In [ ]:
ann.fit(x=X_train, y=y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 970us/step - loss: 0.3367 - accuracy: 0.8633
Epoch 2/100
250/250 [==============================] - 0s 961us/step - loss: 0.3367 - accuracy: 0.8612
Epoch 3/100
250/250 [==============================] - 0s 988us/step - loss: 0.3365 - accuracy: 0.8620
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3371 - accuracy: 0.8611
Epoch 5/100
250/250 [==============================] - 0s 980us/step - loss: 0.3370 - accuracy: 0.8631
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3369 - accuracy: 0.8625
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3364 - accuracy: 0.8626
Epoch 8/100
250/250 [==============================] - 0s 988us/step - loss: 0.3363 - accuracy: 0.8605
Epoch 9/100
250/250 [==============================] - 0s 992us/step - loss: 0.3361 - accuracy: 0.8630
Epoch 10/100
250/250 [==============================] - 0s 990us/step - loss: 0

In [ ]:
y_predict = ann.predict(X_test)
y_predict = [1 if i >.5 else 0 for i in y_predict]
print(y_predict)

[0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
import seaborn as sns 
cm = confusion_matrix(y_test, y_predict)
print(cm)
accuracy_score(y_test, y_predict)

[[1537   58]
 [ 209  196]]


0.8665